# Build stage
FROM node:{{.LanguageVersion}}-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .
{{- if .HasBuild}}
RUN npm run build
{{- end}}

# Run stage
FROM node:{{.LanguageVersion}}-alpine

RUN apk add --no-cache dumb-init

WORKDIR /app
COPY --from=builder /app .

EXPOSE {{.Port}}

ENTRYPOINT ["dumb-init", "--"]
CMD ["node", "{{.EntryPoint}}"]
