package config

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/mouhamedsylla/kaal/internal/kaalerr"
	"gopkg.in/yaml.v3"
)

const (
	FileName   = "kaal.yaml"
	APIVersion = "kaal/v1"
)

// Load finds and parses kaal.yaml, starting from dir and walking up to the fs root.
func Load(dir string) (*Config, error) {
	path, err := findConfigFile(dir)
	if err != nil {
		return nil, err
	}
	return loadFromPath(path)
}

// LoadFromPath parses kaal.yaml at an explicit path.
func LoadFromPath(path string) (*Config, error) {
	return loadFromPath(path)
}

func loadFromPath(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, &kaalerr.ConfigError{Path: path, Cause: err}
	}

	var cfg Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, &kaalerr.ConfigError{Path: path, Cause: fmt.Errorf("invalid YAML: %w", err)}
	}

	if err := Validate(&cfg); err != nil {
		return nil, &kaalerr.ConfigError{Path: path, Cause: err}
	}

	return &cfg, nil
}

// findConfigFile walks up from dir until it finds kaal.yaml or hits the fs root.
func findConfigFile(dir string) (string, error) {
	dir, err := filepath.Abs(dir)
	if err != nil {
		return "", err
	}

	for {
		candidate := filepath.Join(dir, FileName)
		if _, err := os.Stat(candidate); err == nil {
			return candidate, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}

	return "", &kaalerr.ConfigError{Cause: fmt.Errorf("%s not found (run 'kaal init' to create one)", FileName)}
}

// Save writes the config back to kaal.yaml at the given path.
func Save(cfg *Config, path string) error {
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("cannot marshal config: %w", err)
	}

	header := []byte("# Generated by kaal — do not edit by hand unless you know what you're doing.\napiVersion: " + APIVersion + "\n")
	_ = header // prepend header manually if needed

	return os.WriteFile(path, data, 0644)
}
