package config

import (
	"fmt"
	"os"
	"path/filepath"

	pilotErr "github.com/mouhamedsylla/pilot/internal/domain/errors"
	"gopkg.in/yaml.v3"
)

const (
	FileName   = "pilot.yaml"
	APIVersion = "pilot/v1"
)

// Load finds and parses pilot.yaml, starting from dir and walking up to the fs root.
func Load(dir string) (*Config, error) {
	path, err := findConfigFile(dir)
	if err != nil {
		return nil, err
	}
	return loadFromPath(path)
}

// LoadFromPath parses pilot.yaml at an explicit path.
func LoadFromPath(path string) (*Config, error) {
	return loadFromPath(path)
}

func loadFromPath(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, pilotErr.NewTypeD(
			"PILOT-CFG-001",
			fmt.Sprintf("cannot read %s", path),
			fmt.Sprintf("Verify the file exists and is readable:\n  ls -la %s", path),
			pilotErr.ExitConfig,
			pilotErr.WithCause(err),
		)
	}

	var cfg Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, pilotErr.NewTypeD(
			"PILOT-CFG-002",
			fmt.Sprintf("invalid YAML in %s", path),
			fmt.Sprintf("Fix the YAML syntax in %s and run again.", path),
			pilotErr.ExitConfig,
			pilotErr.WithCause(err),
		)
	}

	if err := Validate(&cfg); err != nil {
		return nil, pilotErr.NewTypeD(
			"PILOT-CFG-003",
			fmt.Sprintf("invalid config in %s", path),
			fmt.Sprintf("Fix the validation error in %s:\n  %v", path, err),
			pilotErr.ExitConfig,
			pilotErr.WithCause(err),
		)
	}

	return &cfg, nil
}

// findConfigFile walks up from dir until it finds pilot.yaml or hits the fs root.
func findConfigFile(dir string) (string, error) {
	dir, err := filepath.Abs(dir)
	if err != nil {
		return "", err
	}

	for {
		candidate := filepath.Join(dir, FileName)
		if _, err := os.Stat(candidate); err == nil {
			return candidate, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}

	return "", pilotErr.NewTypeD(
		"PILOT-CFG-001",
		fmt.Sprintf("%s not found", FileName),
		"Run 'pilot init' to create a new project, or cd into an existing pilot project.",
		pilotErr.ExitConfig,
	)
}

// Save writes the config back to pilot.yaml at the given path.
func Save(cfg *Config, path string) error {
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("cannot marshal config: %w", err)
	}

	header := []byte("# Generated by pilot — do not edit by hand unless you know what you're doing.\napiVersion: " + APIVersion + "\n")
	_ = header // prepend header manually if needed

	return os.WriteFile(path, data, 0644)
}
