package scaffold

import (
	"bytes"
	"embed"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

//go:embed templates
var templatesFS embed.FS

// templateData is passed to every template during rendering.
type templateData struct {
	Name            string
	Stack           string
	LanguageVersion string
	Port            int
	Image           string
	HasDB           bool
	HasBuild        bool   // node only — if a build step exists
	EntryPoint      string // node only
}

// Generate creates all project files in opts.OutputDir.
func Generate(opts Options) error {
	opts.applyDefaults()

	dir := opts.OutputDir
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create project dir: %w", err)
	}

	image := buildImageName(opts)
	data := templateData{
		Name:            opts.Name,
		Stack:           opts.Stack,
		LanguageVersion: opts.LanguageVersion,
		Port:            opts.Port,
		Image:           image,
		HasDB:           opts.HasDB,
		HasBuild:        opts.Stack == "node",
		EntryPoint:      "dist/index.js",
	}

	// Stack-specific files
	if err := generateStackFiles(dir, opts.Stack, data); err != nil {
		return err
	}

	// kaal.yaml
	if err := generateKaalYAML(dir, opts, image); err != nil {
		return err
	}

	// .gitignore (only if it doesn't exist)
	gitignorePath := filepath.Join(dir, ".gitignore")
	if _, err := os.Stat(gitignorePath); os.IsNotExist(err) {
		if err := renderTemplate("templates/common/gitignore.tmpl", gitignorePath, data); err != nil {
			return err
		}
	}

	return nil
}

func generateStackFiles(dir, stack string, data templateData) error {
	type fileMapping struct {
		tmpl string
		dest string
	}

	mappings := []fileMapping{
		{fmt.Sprintf("templates/%s/Dockerfile.tmpl", stack), "Dockerfile"},
		{fmt.Sprintf("templates/%s/docker-compose.dev.tmpl", stack), "docker-compose.dev.yml"},
		{fmt.Sprintf("templates/%s/docker-compose.prod.tmpl", stack), "docker-compose.prod.yml"},
		{fmt.Sprintf("templates/%s/env.dev.tmpl", stack), ".env.dev"},
	}

	for _, m := range mappings {
		dest := filepath.Join(dir, m.dest)
		if err := renderTemplate(m.tmpl, dest, data); err != nil {
			// If template doesn't exist for this stack, skip gracefully
			if os.IsNotExist(err) {
				continue
			}
			return err
		}
	}
	return nil
}

func generateKaalYAML(dir string, opts Options, image string) error {
	envBlock := ""
	for _, env := range opts.Environments {
		composeFile := fmt.Sprintf("docker-compose.%s.yml", env)
		envFile := fmt.Sprintf(".env.%s", env)
		envBlock += fmt.Sprintf(`
  %s:
    compose_file: %s
    env_file: %s
    ports:
      api: %d
`, env, composeFile, envFile, opts.Port)
		if opts.HasDB {
			envBlock += fmt.Sprintf("      db: 5432\n")
		}
		if env != "dev" {
			envBlock += fmt.Sprintf("    target: vps-%s\n", env)
		}
	}

	targetBlock := ""
	for _, env := range opts.Environments {
		if env == "dev" {
			continue
		}
		targetBlock += fmt.Sprintf(`
  vps-%s:
    type: vps
    host: ""       # fill in your server IP or hostname
    user: deploy
    key: ~/.ssh/id_kaal
    port: 22
`, env)
	}

	registryURL := ""
	if opts.Registry == "custom" && opts.RegistryURL != "" {
		registryURL = "\n  url: " + opts.RegistryURL
	}

	content := fmt.Sprintf(`# Generated by kaal init — edit to fit your project.
apiVersion: kaal/v1

project:
  name: %s
  stack: %s
  language_version: "%s"

registry:
  provider: %s
  image: %s%s

environments:%s
targets:%s`,
		opts.Name,
		opts.Stack,
		opts.LanguageVersion,
		opts.Registry,
		image,
		registryURL,
		envBlock,
		targetBlock,
	)

	return os.WriteFile(filepath.Join(dir, "kaal.yaml"), []byte(content), 0644)
}

func renderTemplate(tmplPath, destPath string, data templateData) error {
	tmplContent, err := templatesFS.ReadFile(tmplPath)
	if err != nil {
		return err
	}

	tmpl, err := template.New(filepath.Base(tmplPath)).Parse(string(tmplContent))
	if err != nil {
		return fmt.Errorf("parse template %s: %w", tmplPath, err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("render template %s: %w", tmplPath, err)
	}

	if err := os.MkdirAll(filepath.Dir(destPath), 0755); err != nil {
		return err
	}

	return os.WriteFile(destPath, buf.Bytes(), 0644)
}

func buildImageName(opts Options) string {
	if opts.RegistryImage != "" {
		return opts.RegistryImage
	}
	switch opts.Registry {
	case "ghcr":
		return fmt.Sprintf("ghcr.io/YOUR_GITHUB_USER/%s", opts.Name)
	case "dockerhub":
		return fmt.Sprintf("YOUR_DOCKERHUB_USER/%s", opts.Name)
	default:
		return opts.Name
	}
}

// ensure embed is used
var _ embed.FS
