package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/mouhamedsylla/kaal/internal/config"
	"gopkg.in/yaml.v3"
)

// Generate writes kaal.yaml and .mcp.json to opts.OutputDir.
// Dockerfiles and compose files are NOT generated here — the AI agent
// generates them via MCP tools (kaal_generate_dockerfile, kaal_generate_compose).
func Generate(opts Options) error {
	if err := os.MkdirAll(opts.OutputDir, 0755); err != nil {
		return fmt.Errorf("create dir %s: %w", opts.OutputDir, err)
	}

	cfg := opts.ToConfig()

	if err := writeKaalYAML(opts.OutputDir, cfg); err != nil {
		return err
	}

	return writeMCPJSON(opts.OutputDir)
}

// writeMCPJSON creates .mcp.json for AI agent integration (Claude Code, Cursor…).
// Does nothing if the file already exists so manual edits are preserved.
func writeMCPJSON(dir string) error {
	path := filepath.Join(dir, ".mcp.json")
	if _, err := os.Stat(path); err == nil {
		return nil // already exists — preserve user edits
	}
	const content = `{
  "mcpServers": {
    "kaal": {
      "command": "kaal",
      "args": ["mcp", "serve"],
      "cwd": "${workspaceFolder}"
    }
  }
}
`
	return os.WriteFile(path, []byte(content), 0644)
}

func writeKaalYAML(dir string, cfg *config.Config) error {
	path := filepath.Join(dir, config.FileName)

	// Marshal to YAML
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("marshal kaal.yaml: %w", err)
	}

	header := "# Generated by kaal init\n" +
		"# Edit to describe your infrastructure — kaal up reads this at runtime.\n" +
		"# Docs: https://github.com/mouhamedsylla/kaal\n\n"

	content := header + annotate(string(data))
	return os.WriteFile(path, []byte(content), 0644)
}

// annotate adds helpful inline comments to the generated YAML.
func annotate(raw string) string {
	replacements := []struct{ old, new string }{
		{
			"  runtime: compose\n",
			"  runtime: compose  # compose | lima (VM) | k3d (k8s)\n",
		},
		{
			"    host: \"\"\n",
			"    host: \"\"  # fill in: IP address or hostname\n",
		},
		{
			"    key: ~/.ssh/id_kaal\n",
			"    key: ~/.ssh/id_kaal  # SSH private key path\n",
		},
	}
	for _, r := range replacements {
		raw = strings.ReplaceAll(raw, r.old, r.new)
	}
	return raw
}
