package composer

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/mouhamedsylla/kaal/internal/config"
	"github.com/mouhamedsylla/kaal/internal/scaffold"
)

// EnsureDockerfile checks if a Dockerfile exists at the project root.
// If not, it generates a minimal production-ready one based on the detected stack.
// Returns the Dockerfile path and whether it was generated (vs already existing).
func EnsureDockerfile(cfg *config.Config) (path string, generated bool, err error) {
	path = "Dockerfile"

	// Check for an explicit dockerfile path in the app service
	for _, svc := range cfg.Services {
		if svc.Type == config.ServiceTypeApp && svc.Dockerfile != "" {
			path = svc.Dockerfile
			break
		}
	}

	if _, err := os.Stat(path); err == nil {
		return path, false, nil // already exists — use it
	}

	// Detect stack from project files
	detected := scaffold.Detect(".")
	stack := detected.Stack
	if stack == "" && cfg.Project.Stack != "" {
		stack = cfg.Project.Stack
	}
	if stack == "" {
		return "", false, fmt.Errorf(
			"no Dockerfile found and stack could not be detected\n" +
				"  Add a Dockerfile or set project.stack in kaal.yaml",
		)
	}

	langVersion := cfg.Project.LanguageVersion
	if langVersion == "" {
		langVersion = detected.LanguageVersion
	}

	port := 8080
	for _, svc := range cfg.Services {
		if svc.Type == config.ServiceTypeApp && svc.Port > 0 {
			port = svc.Port
			break
		}
	}

	content, err := generateDockerfile(stack, langVersion, port)
	if err != nil {
		return "", false, err
	}

	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return "", false, fmt.Errorf("write Dockerfile: %w", err)
	}

	return path, true, nil
}

// DockerfileExists returns true if a Dockerfile is present at the given path.
func DockerfileExists(path string) bool {
	if path == "" {
		path = "Dockerfile"
	}
	_, err := os.Stat(path)
	return err == nil
}

// AppDockerfilePath returns the configured Dockerfile path for the app service,
// or "Dockerfile" if not set.
func AppDockerfilePath(cfg *config.Config) string {
	for _, svc := range cfg.Services {
		if svc.Type == config.ServiceTypeApp && svc.Dockerfile != "" {
			return filepath.Clean(svc.Dockerfile)
		}
	}
	return "Dockerfile"
}

func generateDockerfile(stack, langVersion string, port int) (string, error) {
	return generateDockerfileContent(stack, langVersion, port)
}

func generateDockerfileContent(stack, langVersion string, port int) (string, error) {
	switch stack {
	case "go":
		if langVersion == "" {
			langVersion = "1.23"
		}
		return fmt.Sprintf(`# Generated by kaal up
# Optimized multi-stage build for Go %s

FROM golang:%s-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /app/server .

FROM alpine:3.20
RUN apk add --no-cache ca-certificates tzdata
WORKDIR /app
COPY --from=builder /app/server .
EXPOSE %d
ENTRYPOINT ["/app/server"]
`, langVersion, langVersion, port), nil

	case "node":
		if langVersion == "" {
			langVersion = "20"
		}
		return fmt.Sprintf(`# Generated by kaal up
FROM node:%s-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build 2>/dev/null || true

FROM node:%s-alpine
RUN apk add --no-cache dumb-init
WORKDIR /app
COPY --from=builder /app .
RUN npm prune --production
EXPOSE %d
ENTRYPOINT ["dumb-init", "--"]
CMD ["node", "dist/index.js"]
`, langVersion, langVersion, port), nil

	case "python":
		if langVersion == "" {
			langVersion = "3.12"
		}
		return fmt.Sprintf(`# Generated by kaal up
FROM python:%s-slim
WORKDIR /app
COPY requirements*.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE %d
CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "%d"]
`, langVersion, port, port), nil

	case "rust":
		if langVersion == "" {
			langVersion = "1.82"
		}
		return fmt.Sprintf(`# Generated by kaal up
FROM rust:%s-alpine AS builder
RUN apk add --no-cache musl-dev
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs && cargo build --release && rm -rf src
COPY . .
RUN touch src/main.rs && cargo build --release

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
COPY --from=builder /app/target/release/app /usr/local/bin/app
EXPOSE %d
ENTRYPOINT ["/usr/local/bin/app"]
`, langVersion, port), nil

	case "java":
		return fmt.Sprintf(`# Generated by kaal up
FROM eclipse-temurin:21-jdk-alpine AS builder
WORKDIR /app
COPY . .
RUN ./mvnw package -DskipTests 2>/dev/null || ./gradlew build -x test

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar 2>/dev/null || \
     COPY --from=builder /app/build/libs/*.jar app.jar
EXPOSE %d
ENTRYPOINT ["java", "-jar", "app.jar"]
`, port), nil

	default:
		return "", fmt.Errorf("stack %q not supported for Dockerfile generation\n"+
			"  Add a Dockerfile manually or set services.<name>.dockerfile in kaal.yaml", stack)
	}
}
