// Package lock manages pilot.lock — the validated, committed snapshot of
// what pilot will do on the next operation.
//
// The lock is generated once by `pilot preflight`, committed to the repo,
// and used as the source of truth for every subsequent execution.
// If the files that produced the lock change, it becomes stale and pilot
// refuses to continue until `pilot preflight` regenerates it.
package lock

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/mouhamedsylla/pilot/internal/domain/plan"
)

const lockFile = "pilot.lock"

// ErrNotFound is returned by Read when pilot.lock does not exist yet.
var ErrNotFound = errors.New("pilot.lock not found — run: pilot preflight")

// Lock is the validated execution plan for a project.
// It is generated by `pilot preflight` and committed to the repo.
type Lock struct {
	SchemaVersion int       `yaml:"schema_version"`
	GeneratedAt   time.Time `yaml:"generated_at"`
	GeneratedFrom []string  `yaml:"generated_from"`

	// ProjectHash is a content hash of the files in GeneratedFrom.
	// If it changes, the lock is stale.
	ProjectHash string `yaml:"project_hash"`

	ExecutionPlan     ExecutionPlan `yaml:"execution_plan"`
	ExecutionProvider string        `yaml:"execution_provider"` // compose | systemd | k8s
}

// ExecutionPlan describes the active nodes and their configuration.
type ExecutionPlan struct {
	NodesActive  []plan.StepName  `yaml:"nodes_active"`
	Migrations   *MigrationConfig `yaml:"migrations,omitempty"`
	ServiceOrder []string         `yaml:"service_order,omitempty"`
}

// MigrationConfig holds the validated migration tool and commands.
type MigrationConfig struct {
	Tool            string `yaml:"tool"`             // prisma | alembic | goose | ...
	Command         string `yaml:"command"`          // command to apply migrations
	RollbackCommand string `yaml:"rollback_command"` // required when reversible: true
	Reversible      bool   `yaml:"reversible"`       // false by default — declare explicitly
	DetectedFrom    string `yaml:"detected_from"`    // file that triggered detection
}

// IsStale reports whether the lock must be regenerated.
// The lock is stale when the content hash of the source files has changed.
func (l *Lock) IsStale(currentHash string) bool {
	return l.ProjectHash == "" || l.ProjectHash != currentHash
}

// ActiveNodes returns the set of step names enabled in this lock.
func (l *Lock) ActiveNodes() map[plan.StepName]bool {
	out := make(map[plan.StepName]bool, len(l.ExecutionPlan.NodesActive))
	for _, n := range l.ExecutionPlan.NodesActive {
		out[n] = true
	}
	return out
}

// Write persists the lock to <dir>/pilot.lock (YAML, human-readable).
func (l *Lock) Write(dir string) error {
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("lock: create dir: %w", err)
	}
	data, err := yaml.Marshal(l)
	if err != nil {
		return fmt.Errorf("lock: marshal: %w", err)
	}
	header := []byte("# pilot.lock — generated automatically, commit this file.\n" +
		"# DO NOT EDIT MANUALLY — run: pilot preflight\n\n")
	if err := os.WriteFile(filepath.Join(dir, lockFile), append(header, data...), 0644); err != nil {
		return fmt.Errorf("lock: write: %w", err)
	}
	return nil
}

// Read loads pilot.lock from <dir>/pilot.lock.
// Returns ErrNotFound if the file does not exist.
func Read(dir string) (*Lock, error) {
	data, err := os.ReadFile(filepath.Join(dir, lockFile))
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("lock: read: %w", err)
	}
	var l Lock
	if err := yaml.Unmarshal(data, &l); err != nil {
		return nil, fmt.Errorf("lock: unmarshal: %w", err)
	}
	return &l, nil
}
