package handlers

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/mouhamedsylla/pilot/internal/adapters/secrets/local"
	pilotenv "github.com/mouhamedsylla/pilot/internal/env"
)

// HandleEnvCreate creates .env.<env> from .env.example with:
//   - cryptographically secure generated values for secrets/keys
//   - sensible defaults for common config vars
//   - documented placeholders with instructions for external credentials
//
// Never overwrites an existing file. Never reads values from other env files.
func HandleEnvCreate(_ context.Context, params map[string]any) (any, error) {
	env := strParam(params, "env")
	if env == "" {
		env = pilotenv.Active("")
	}

	targetFile := fmt.Sprintf(".env.%s", env)

	// Never overwrite
	if _, err := os.Stat(targetFile); err == nil {
		return nil, fmt.Errorf(
			"%s already exists — delete it first if you want to regenerate it", targetFile,
		)
	}

	// .env.example is the only legitimate source
	const exampleFile = ".env.example"
	if _, err := os.Stat(exampleFile); os.IsNotExist(err) {
		return nil, fmt.Errorf(
			"no .env.example found — create one with the variable names your app needs",
		)
	}

	vars, err := local.ListFile(exampleFile)
	if err != nil {
		return nil, fmt.Errorf("env_create: read .env.example: %w", err)
	}
	if len(vars) == 0 {
		return map[string]any{
			"env":     env,
			"file":    targetFile,
			"created": false,
			"note":    ".env.example is empty — nothing to create",
		}, nil
	}

	// Classify and resolve every variable
	generated := []string{}
	defaulted := []string{}
	external := []string{}
	unknown := []string{}

	type resolved struct {
		value   string
		comment string // empty = no comment above
		section string // generated | defaults | external | unknown
	}

	resolutions := make(map[string]resolved, len(vars))

	for name := range vars {
		upper := strings.ToUpper(name)

		switch {
		case isGeneratable(upper):
			val, err := generateSecret()
			if err != nil {
				return nil, fmt.Errorf("env_create: generate secret for %s: %w", name, err)
			}
			resolutions[name] = resolved{value: val, section: "generated"}
			generated = append(generated, name)

		case hasDefault(upper):
			resolutions[name] = resolved{value: defaultValue(upper), section: "defaults"}
			defaulted = append(defaulted, name)

		case isExternal(upper):
			info := externalInfo(upper)
			resolutions[name] = resolved{
				value:   "",
				comment: fmt.Sprintf("# %s\n# → %s", info.label, info.instructions),
				section: "external",
			}
			external = append(external, name)

		default:
			resolutions[name] = resolved{
				value:   "",
				comment: "# TODO: set this value",
				section: "unknown",
			}
			unknown = append(unknown, name)
		}
	}

	// Build the file content
	var sb strings.Builder

	// Header
	sb.WriteString(fmt.Sprintf("# Generated by pilot-agent — %s\n", time.Now().Format("2006-01-02")))
	sb.WriteString(fmt.Sprintf("# Environment : %s\n", env))
	sb.WriteString("# Source      : .env.example\n")
	sb.WriteString("#\n")
	sb.WriteString(fmt.Sprintf("# ✓ %d value(s) generated automatically\n", len(generated)))
	sb.WriteString(fmt.Sprintf("# ✓ %d value(s) set to defaults\n", len(defaulted)))
	if len(external) > 0 {
		sb.WriteString(fmt.Sprintf("# ✗ %d value(s) require manual configuration (see comments below)\n", len(external)))
	}
	if len(unknown) > 0 {
		sb.WriteString(fmt.Sprintf("# ? %d value(s) unknown — review required\n", len(unknown)))
	}
	sb.WriteString("#\n# DO NOT COMMIT THIS FILE\n")

	// Write by section to keep the file readable
	writeSection := func(title string, names []string) {
		if len(names) == 0 {
			return
		}
		sort.Strings(names)
		sb.WriteString(fmt.Sprintf("\n# ── %s ", title))
		sb.WriteString(strings.Repeat("─", max(0, 60-len(title))))
		sb.WriteString("\n")
		for _, name := range names {
			r := resolutions[name]
			if r.comment != "" {
				sb.WriteString(r.comment + "\n")
			}
			if r.value != "" {
				sb.WriteString(fmt.Sprintf("%s=%s\n", name, r.value))
			} else {
				sb.WriteString(fmt.Sprintf("%s=\n", name))
			}
		}
	}

	writeSection("Generated (cryptographically secure)", generated)
	writeSection("Defaults", defaulted)
	writeSection("External credentials — manual setup required", external)
	writeSection("Unknown — review required", unknown)

	// Write file (mode 0600 — owner only)
	if err := os.WriteFile(targetFile, []byte(sb.String()), 0600); err != nil {
		return nil, fmt.Errorf("env_create: write %s: %w", targetFile, err)
	}

	// Build result report
	externalList := make([]map[string]string, 0, len(external))
	sort.Strings(external)
	for _, name := range external {
		info := externalInfo(strings.ToUpper(name))
		externalList = append(externalList, map[string]string{
			"name":         name,
			"instructions": info.instructions,
		})
	}

	return map[string]any{
		"env":       env,
		"file":      targetFile,
		"created":   true,
		"generated": generated,
		"defaulted": defaulted,
		"external":  externalList,
		"unknown":   unknown,
		"note": fmt.Sprintf(
			"Created %s. %d value(s) need manual configuration — open the file and fill the empty lines.",
			targetFile, len(external)+len(unknown),
		),
	}, nil
}

// ── Secret generation ─────────────────────────────────────────────────────────

func generateSecret() (string, error) {
	b := make([]byte, 32) // 256 bits → 64 hex chars
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

// ── Variable classification ───────────────────────────────────────────────────

var generateKeywords = []string{
	"secret", "jwt", "signing_key", "hash_key", "app_key", "master_key",
	"private_key", "token_secret", "auth_key", "session_key", "encryption_key",
	"crypto_key", "hmac_key", "api_secret", "webhook_secret",
}

func isGeneratable(upper string) bool {
	lower := strings.ToLower(upper)
	for _, kw := range generateKeywords {
		if strings.Contains(lower, kw) {
			return true
		}
	}
	return false
}

var defaultValues = map[string]string{
	"PORT": "8080", "APP_PORT": "8080", "SERVER_PORT": "8080", "HTTP_PORT": "8080",
	"APP_ENV": "production", "NODE_ENV": "production", "GO_ENV": "production",
	"PYTHON_ENV": "production", "ENVIRONMENT": "production", "RAILS_ENV": "production",
	"GIN_MODE": "release",
	"LOG_LEVEL": "info", "LOG_FORMAT": "json",
	"REDIS_URL": "redis://localhost:6379", "REDIS_HOST": "localhost", "REDIS_PORT": "6379",
	"APP_HOST": "0.0.0.0",
	"TZ": "UTC", "TIMEZONE": "UTC",
}

func hasDefault(upper string) bool {
	_, ok := defaultValues[upper]
	return ok
}

func defaultValue(upper string) string {
	return defaultValues[upper]
}

// ── External providers ────────────────────────────────────────────────────────

type extInfo struct {
	label        string
	instructions string
}

var externalProviders = map[string]extInfo{
	// Google
	"GOOGLE_CLIENT_ID":     {"Google OAuth Client ID", "console.cloud.google.com › APIs & Services › Credentials › Create OAuth 2.0 Client ID"},
	"GOOGLE_CLIENT_SECRET": {"Google OAuth Client Secret", "console.cloud.google.com › APIs & Services › Credentials"},
	"GOOGLE_API_KEY":       {"Google API Key", "console.cloud.google.com › APIs & Services › Credentials › Create API Key"},

	// GitHub
	"GITHUB_CLIENT_ID":     {"GitHub OAuth App Client ID", "github.com/settings/developers › New OAuth App"},
	"GITHUB_CLIENT_SECRET": {"GitHub OAuth App Client Secret", "github.com/settings/developers › New OAuth App"},
	"GITHUB_TOKEN":         {"GitHub Personal Access Token", "github.com/settings/tokens › Generate new token (classic)"},

	// Apple
	"APPLE_CLIENT_ID": {"Apple Sign In Service ID", "developer.apple.com › Certificates, IDs & Profiles › Identifiers › Services IDs"},
	"APPLE_TEAM_ID":   {"Apple Developer Team ID", "developer.apple.com › Account › top-right corner"},
	"APPLE_KEY_ID":    {"Apple Sign In Key ID", "developer.apple.com › Certificates, IDs & Profiles › Keys"},

	// Stripe
	"STRIPE_SECRET_KEY":      {"Stripe Secret Key (sk_live_...)", "dashboard.stripe.com/apikeys"},
	"STRIPE_PUBLISHABLE_KEY": {"Stripe Publishable Key (pk_live_...)", "dashboard.stripe.com/apikeys"},
	"STRIPE_WEBHOOK_SECRET":  {"Stripe Webhook Signing Secret", "dashboard.stripe.com/webhooks › Add endpoint › Signing secret"},

	// Supabase
	"SUPABASE_URL":              {"Supabase Project URL", "app.supabase.com › Project Settings › API › Project URL"},
	"SUPABASE_ANON_KEY":         {"Supabase Anon Key (public — safe for frontend)", "app.supabase.com › Project Settings › API › Project API keys"},
	"SUPABASE_SERVICE_ROLE_KEY": {"Supabase Service Role Key (secret — backend only, never expose client-side)", "app.supabase.com › Project Settings › API › Project API keys"},

	// Neon
	"NEON_DATABASE_URL": {"Neon PostgreSQL connection string", "console.neon.tech › Project › Connection Details › Connection string"},

	// PlanetScale
	"PLANETSCALE_DATABASE_URL": {"PlanetScale MySQL connection string", "app.planetscale.com › Connect › Connect with › PHP (or other) for the DSN"},

	// Upstash
	"UPSTASH_REDIS_REST_URL":   {"Upstash Redis REST URL", "console.upstash.com › Redis › your db › REST API › UPSTASH_REDIS_REST_URL"},
	"UPSTASH_REDIS_REST_TOKEN": {"Upstash Redis REST Token", "console.upstash.com › Redis › your db › REST API › UPSTASH_REDIS_REST_TOKEN"},

	// Database (generic)
	"DATABASE_URL":  {"Database connection string — format: postgresql://user:pass@host:5432/dbname", ""},
	"POSTGRES_URL":  {"PostgreSQL connection string — format: postgresql://user:pass@host:5432/dbname", ""},
	"MONGODB_URI":   {"MongoDB connection URI — format: mongodb+srv://user:pass@cluster.mongodb.net/db", "cloud.mongodb.com › Connect › Connect your application"},
	"DATABASE_HOST": {"Database hostname or IP", ""},

	// AWS
	"AWS_ACCESS_KEY_ID":     {"AWS IAM Access Key ID", "console.aws.amazon.com › IAM › Users › your user › Security credentials › Create access key"},
	"AWS_SECRET_ACCESS_KEY": {"AWS IAM Secret Access Key (shown once at creation)", "console.aws.amazon.com › IAM › Users › your user › Security credentials"},
	"AWS_REGION":            {"AWS Region code (e.g. eu-west-1, us-east-1)", "aws.amazon.com/about-aws/global-infrastructure/regions_az"},

	// Cloudflare
	"CLOUDFLARE_API_TOKEN":  {"Cloudflare API Token", "dash.cloudflare.com/profile/api-tokens › Create Token"},
	"CLOUDFLARE_ACCOUNT_ID": {"Cloudflare Account ID", "dash.cloudflare.com › any domain › right sidebar › Account ID"},
	"CLOUDFLARE_ZONE_ID":    {"Cloudflare Zone ID (per domain)", "dash.cloudflare.com › your domain › right sidebar › Zone ID"},

	// Email
	"SENDGRID_API_KEY":  {"SendGrid API Key", "app.sendgrid.com/settings/api_keys › Create API Key"},
	"RESEND_API_KEY":    {"Resend API Key", "resend.com/api-keys › Create API Key"},
	"MAILGUN_API_KEY":   {"Mailgun API Key", "app.mailgun.com/app/account/security/api_keys"},
	"POSTMARK_API_KEY":  {"Postmark Server API Token", "account.postmarkapp.com › Server › API Tokens"},
	"SMTP_HOST":         {"SMTP server hostname (e.g. smtp.sendgrid.net)", ""},
	"SMTP_USER":         {"SMTP username", ""},
	"SMTP_PASSWORD":     {"SMTP password or API key used as password", ""},

	// Twilio
	"TWILIO_ACCOUNT_SID": {"Twilio Account SID", "console.twilio.com/ › Account Info"},
	"TWILIO_AUTH_TOKEN":  {"Twilio Auth Token", "console.twilio.com/ › Account Info"},

	// AI / LLM
	"OPENAI_API_KEY":    {"OpenAI API Key", "platform.openai.com/api-keys › Create new secret key"},
	"ANTHROPIC_API_KEY": {"Anthropic API Key", "console.anthropic.com/settings/keys › Create Key"},
	"MISTRAL_API_KEY":   {"Mistral API Key", "console.mistral.ai/api-keys"},

	// Monitoring
	"SENTRY_DSN":     {"Sentry DSN", "sentry.io › Settings › Projects › your project › Client Keys (DSN)"},
	"DATADOG_API_KEY": {"Datadog API Key", "app.datadoghq.com/organization-settings/api-keys"},

	// Push / Realtime
	"PUSHER_APP_ID":  {"Pusher App ID", "dashboard.pusher.com › your app › App Keys"},
	"PUSHER_KEY":     {"Pusher Key", "dashboard.pusher.com › your app › App Keys"},
	"PUSHER_SECRET":  {"Pusher Secret", "dashboard.pusher.com › your app › App Keys"},
	"PUSHER_CLUSTER": {"Pusher Cluster (e.g. eu, ap1)", "dashboard.pusher.com › your app › App Keys"},

	// Search
	"ALGOLIA_APP_ID":  {"Algolia Application ID", "www.algolia.com/account/api-keys"},
	"ALGOLIA_API_KEY": {"Algolia Admin API Key", "www.algolia.com/account/api-keys"},

	// Firebase
	"FIREBASE_API_KEY":    {"Firebase API Key", "console.firebase.google.com › Project Settings › General › Your apps › Web API Key"},
	"FIREBASE_PROJECT_ID": {"Firebase Project ID", "console.firebase.google.com › Project Settings › General › Project ID"},

	// Storage
	"S3_BUCKET":            {"AWS S3 bucket name", ""},
	"S3_ACCESS_KEY":        {"S3-compatible access key", ""},
	"S3_SECRET_KEY":        {"S3-compatible secret key", ""},
	"R2_ACCESS_KEY_ID":     {"Cloudflare R2 Access Key ID", "dash.cloudflare.com › R2 › Manage R2 API tokens"},
	"R2_SECRET_ACCESS_KEY": {"Cloudflare R2 Secret Access Key", "dash.cloudflare.com › R2 › Manage R2 API tokens"},

	// OAuth generic
	"OAUTH_CLIENT_ID":     {"OAuth Client ID — check your provider's developer console", ""},
	"OAUTH_CLIENT_SECRET": {"OAuth Client Secret — check your provider's developer console", ""},
}

func isExternal(upper string) bool {
	_, ok := externalProviders[upper]
	return ok
}

func externalInfo(upper string) extInfo {
	if info, ok := externalProviders[upper]; ok {
		return info
	}
	return extInfo{label: upper, instructions: ""}
}

// ── Utils ─────────────────────────────────────────────────────────────────────

func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}
